services:
  backend:
    restart: unless-stopped
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - /home/deploy/lancedb:/app/lancedb
      - /home/deploy/hf-cache:/root/.cache/huggingface
    container_name: muensterportal-api
